version: 2
project_name: awas

builds:
  - tool: garble
    command: "-literals"
    flags:
      - build
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: awas
    ldflags:
      - -s -w -X main.Version={{.Version}}
    dir: .
    main: .

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: jimbon25
    name: awas-agent
